pipeline {
    agent any
    stages {
        stage('Build image') {
            steps {
                BTC_VERSION="22.0"
                git(url: 'https://github.com/stevenheinze57/practical-test.git', branch: 'master')
                sh(script: "docker build --build-arg "BTC_VERSION=${BTC_VERSION}" -t bitcoin:${BTC_VERSION} -f Dockerfile . ")
                //kubernetesApply(createNewResources: true, deletePodsOnReplicationControllerUpdate: false, ignoreRunningOAuthClients: false, ignoreServices: false, processTemplatesLocally: false, readinessTimeout: 0, rollingUpgradePreserveScale: true, rollingUpgrades: true, servicesOnly: false)
            }
        }
    }
}